# JSON generated by https://www.json-generator.com
curl -i -X POST -H "Content-Type: application/json" -d '[
  {
    "_id": "5e078582583fc75b7e7f1c67",
    "index": 0,
    "guid": "83cde7e3-f612-4e97-bf90-3e1f4d18a712",
    "isActive": true,
    "balance": "$2,266.04",
    "picture": "http://placehold.it/32x32",
    "age": 32,
    "eyeColor": "blue",
    "name": "Janelle Molina",
    "gender": "female",
    "company": "MANTRO",
    "email": "janellemolina@mantro.com",
    "phone": "+1 (994) 589-2416",
    "address": "959 Schenck Avenue, Fontanelle, Alaska, 596",
    "about": "Et ullamco cillum esse enim officia aliqua quis eiusmod veniam ullamco dolore. Et fugiat qui proident sit nostrud est dolore eu nostrud excepteur. Sit cupidatat aute pariatur consequat quis nisi id elit id minim cupidatat non. Ea duis ullamco laborum ipsum.\r\n",
    "registered": "2019-07-20T04:47:01 -02:00",
    "latitude": 68.083637,
    "longitude": 36.389009,
    "tags": [
      "irure",
      "quis",
      "sit",
      "labore",
      "occaecat",
      "adipisicing",
      "deserunt"
    ],
    "friends": [
      {
        "id": 0,
        "name": "Silva Vance"
      },
      {
        "id": 1,
        "name": "Audra Hall"
      },
      {
        "id": 2,
        "name": "Leach Tillman"
      }
    ],
    "greeting": "Hello, Janelle Molina! You have 6 unread messages.",
    "favoriteFruit": "apple"
  },
  {
    "_id": "5e078582f566d14f9fb38bab",
    "index": 1,
    "guid": "2862ce49-0142-4f1a-b479-11595e827f75",
    "isActive": false,
    "balance": "$2,960.62",
    "picture": "http://placehold.it/32x32",
    "age": 33,
    "eyeColor": "green",
    "name": "Catherine Wilcox",
    "gender": "female",
    "company": "ZILLADYNE",
    "email": "catherinewilcox@zilladyne.com",
    "phone": "+1 (836) 573-3954",
    "address": "820 Bulwer Place, Sardis, Pennsylvania, 123",
    "about": "Esse ut in cupidatat qui occaecat labore. Ipsum dolore deserunt id reprehenderit eiusmod veniam ullamco ullamco. Ipsum aliquip enim laboris exercitation esse aliquip. Pariatur pariatur ea aute ex elit. Et voluptate aute pariatur amet magna pariatur laboris culpa.\r\n",
    "registered": "2016-09-07T04:07:40 -02:00",
    "latitude": -55.018038,
    "longitude": 121.958674,
    "tags": [
      "dolore",
      "esse",
      "laboris",
      "sint",
      "mollit",
      "excepteur",
      "incididunt"
    ],
    "friends": [
      {
        "id": 0,
        "name": "Holden Riggs"
      },
      {
        "id": 1,
        "name": "Raymond Nguyen"
      },
      {
        "id": 2,
        "name": "Adriana Rosario"
      }
    ],
    "greeting": "Hello, Catherine Wilcox! You have 9 unread messages.",
    "favoriteFruit": "apple"
  },
  {
    "_id": "5e078582f9972c82d9f4be3e",
    "index": 2,
    "guid": "84a8b9e5-9b56-4f09-abc0-cd718b3036c2",
    "isActive": false,
    "balance": "$3,261.97",
    "picture": "http://placehold.it/32x32",
    "age": 23,
    "eyeColor": "green",
    "name": "Essie Salas",
    "gender": "female",
    "company": "DANCERITY",
    "email": "essiesalas@dancerity.com",
    "phone": "+1 (817) 579-3796",
    "address": "699 Arlington Avenue, Bayview, Northern Mariana Islands, 8386",
    "about": "Cillum commodo voluptate tempor labore eu ut id eiusmod sunt dolor. Dolor sint irure ipsum amet proident. Et irure nisi adipisicing do ullamco cillum cillum officia et. Sint sunt consectetur id nisi do cillum fugiat ad cillum eiusmod voluptate irure. Aliqua sit consequat amet duis adipisicing cillum laboris reprehenderit amet sunt et nostrud.\r\n",
    "registered": "2016-02-03T10:22:40 -01:00",
    "latitude": -14.787179,
    "longitude": 62.698942,
    "tags": [
      "officia",
      "enim",
      "ex",
      "enim",
      "commodo",
      "qui",
      "cupidatat"
    ],
    "friends": [
      {
        "id": 0,
        "name": "Pauline Jordan"
      },
      {
        "id": 1,
        "name": "Luz Dickerson"
      },
      {
        "id": 2,
        "name": "Wolfe Stark"
      }
    ],
    "greeting": "Hello, Essie Salas! You have 6 unread messages.",
    "favoriteFruit": "strawberry"
  },
  {
    "_id": "5e078582801381e0a11aa82f",
    "index": 3,
    "guid": "0cd4508e-abda-4041-8db6-ec52c8f85161",
    "isActive": true,
    "balance": "$1,475.11",
    "picture": "http://placehold.it/32x32",
    "age": 25,
    "eyeColor": "blue",
    "name": "Knowles Stein",
    "gender": "male",
    "company": "ENTALITY",
    "email": "knowlesstein@entality.com",
    "phone": "+1 (880) 479-3173",
    "address": "334 Seigel Court, Tivoli, California, 6597",
    "about": "Do qui aliquip esse et exercitation consectetur laboris quis laborum reprehenderit amet. Cillum nostrud fugiat ipsum ea fugiat Lorem nostrud consectetur aute mollit non esse. Proident sint ex laboris et irure culpa est. Laborum do sunt officia fugiat adipisicing laboris aute velit quis incididunt reprehenderit. Dolor ea veniam aute officia tempor non et. Minim ea minim mollit nostrud culpa ipsum enim sunt consequat in magna proident ad. Id fugiat aute qui quis nisi elit Lorem magna pariatur dolore consequat tempor irure voluptate.\r\n",
    "registered": "2019-03-05T08:01:16 -01:00",
    "latitude": 70.981784,
    "longitude": -109.721082,
    "tags": [
      "nisi",
      "voluptate",
      "excepteur",
      "est",
      "incididunt",
      "non",
      "quis"
    ],
    "friends": [
      {
        "id": 0,
        "name": "Rosie Morin"
      },
      {
        "id": 1,
        "name": "Bartlett Reilly"
      },
      {
        "id": 2,
        "name": "Clarice Mcknight"
      }
    ],
    "greeting": "Hello, Knowles Stein! You have 7 unread messages.",
    "favoriteFruit": "apple"
  },
  {
    "_id": "5e0785822f8722edef538985",
    "index": 4,
    "guid": "bb17e43e-3877-45c6-bead-ae16d2126300",
    "isActive": true,
    "balance": "$1,320.28",
    "picture": "http://placehold.it/32x32",
    "age": 35,
    "eyeColor": "green",
    "name": "Best Wiggins",
    "gender": "male",
    "company": "INEAR",
    "email": "bestwiggins@inear.com",
    "phone": "+1 (999) 445-2206",
    "address": "305 Anchorage Place, Oberlin, South Carolina, 5308",
    "about": "Ullamco laborum ipsum dolor aliquip pariatur consequat ut nisi irure aliquip fugiat consequat consectetur esse. Ex nostrud ipsum exercitation ex culpa id nostrud dolor ex occaecat aliquip tempor veniam. Commodo elit commodo mollit voluptate cupidatat ea amet veniam Lorem sit culpa. Non id consequat pariatur culpa nisi enim voluptate cupidatat. Dolor velit officia consequat sit nostrud Lorem ut laboris ipsum irure.\r\n",
    "registered": "2019-02-25T08:34:54 -01:00",
    "latitude": 47.516654,
    "longitude": -22.088221,
    "tags": [
      "dolor",
      "commodo",
      "eiusmod",
      "consequat",
      "duis",
      "deserunt",
      "ea"
    ],
    "friends": [
      {
        "id": 0,
        "name": "Daniel Cobb"
      },
      {
        "id": 1,
        "name": "Mccarthy Blankenship"
      },
      {
        "id": 2,
        "name": "Della Dixon"
      }
    ],
    "greeting": "Hello, Best Wiggins! You have 5 unread messages.",
    "favoriteFruit": "apple"
  },
  {
    "_id": "5e0785820422f6fdf8718ecd",
    "index": 5,
    "guid": "b06fae1b-6380-4911-8c39-3f595976bdcb",
    "isActive": true,
    "balance": "$2,909.99",
    "picture": "http://placehold.it/32x32",
    "age": 22,
    "eyeColor": "blue",
    "name": "Lara Green",
    "gender": "female",
    "company": "ZILLATIDE",
    "email": "laragreen@zillatide.com",
    "phone": "+1 (979) 421-2553",
    "address": "370 Bush Street, Efland, Hawaii, 9720",
    "about": "Qui deserunt nisi et deserunt mollit laborum aliqua duis aute ut laboris magna non. Excepteur laboris commodo quis cupidatat non enim. Id aliquip proident consequat minim eu consectetur ad fugiat ipsum. Non commodo elit deserunt dolor et ex est tempor veniam cupidatat.\r\n",
    "registered": "2015-01-19T12:23:34 -01:00",
    "latitude": 20.894192,
    "longitude": 102.306183,
    "tags": [
      "anim",
      "consectetur",
      "ex",
      "pariatur",
      "velit",
      "duis",
      "qui"
    ],
    "friends": [
      {
        "id": 0,
        "name": "Jolene Ruiz"
      },
      {
        "id": 1,
        "name": "Candy Albert"
      },
      {
        "id": 2,
        "name": "Ball Flowers"
      }
    ],
    "greeting": "Hello, Lara Green! You have 9 unread messages.",
    "favoriteFruit": "banana"
  }
]' localhost:8080/toto
